DROP DATABASE IF EXISTS rosesignals;
CREATE DATABASE IF NOT EXISTS rosesignals;
USE rosesignals;

CREATE TABLE user(
	id_user CHAR(32) UNIQUE PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    genre CHAR(1) NOT NULL,
    birth_date DATE NOT NULL,
    address MEDIUMTEXT,
    image VARCHAR(255),
    permission VARCHAR(50) DEFAULT 'membro',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE topic(
	id_topic INTEGER AUTO_INCREMENT PRIMARY KEY,
    title LONGTEXT NOT NULL,
    description LONGTEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_id CHAR(32),
    FOREIGN KEY(user_id) REFERENCES user(id_user) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE reaction(
	id_reaction INTEGER AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(25) NOT NULL,
    commentary LONGTEXT,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    topic_id INTEGER,
    FOREIGN KEY(topic_id) REFERENCES topic(id_topic) ON DELETE CASCADE ON UPDATE CASCADE,
    user_id CHAR(32),
    FOREIGN KEY(user_id) REFERENCES user(id_user) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE spreadsheet(
	id_spreadsheet INTEGER AUTO_INCREMENT PRIMARY KEY,
    name_spreadsheet VARCHAR(255) NOT NULL,
    initial_bankroll DECIMAL(12,2) NOT NULL,
    objective DECIMAL(12,2) NOT NULL,
    daily_profit DECIMAL(12,2) NOT NULL,
    payout DECIMAL(5,2) NOT NULL,
    in_box DECIMAL(12,2) NOT NULL,
    type_spreadsheet CHAR(7) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	user_id CHAR(32),
    FOREIGN KEY(user_id) REFERENCES user(id_user) ON DELETE CASCADE ON UPDATE CASCADE
);

SELECT * FROM user;
SELECT * FROM topic;
SELECT * FROM reaction;
SELECT * FROM spreadsheet;